Manually install xorgproto and force overwrite
xorgproto is required by graphviz however it
requires overwriting some symlinks.

> Error: The `brew link` step did not complete successfully
> The formula built, but is not symlinked into /usr/local
> Could not symlink include/X11
> Target /usr/local/include/X11
> already exists. You may want to remove it:
>   rm '/usr/local/include/X11'
>
> To force the link and overwrite all conflicting files:
>   brew link --overwrite xorgproto

Recursive force overwrites were introduced
[in Homebrew 3.4.0](https://brew.sh/2022/02/28/homebrew-3.4.0/)
which isn't yet included in the build images.